blueprint:
  name: Daan Dobber's Scene Cycle (multiple triggers)
  description: Cycles through and activates scenes based on multiple triggers.
  domain: automation

  input:
    trigger_entities:
      name: Trigger Entities
      description: Choose the entities that will trigger the scene cycle.
      selector:
        entity:
          multiple: true
    input_select_entity:
      name: Input Select Entity
      description: The input select entity containing the scenes to cycle through.
      selector:
        entity:
          domain: input_select

trigger:
  - platform: state
    entity_id: !input trigger_entities

action:
  - service: input_select.select_next
    data:
      cycle: true
    target:
      entity_id: !input input_select_entity
  - variables:
      input_select: !input input_select_entity
      selected_scene: "{{ states(input_select) }}"
  - service: scene.turn_on
    data:
      entity_id: "{{ selected_scene }}"
mode: restart
