blueprint:
  name: "Daan Dobber's Scene Cycle with input_select"
  description: Cycles through and activates scenes using a user-defined trigger. First make an input_select helper to define the scenes.
  domain: automation
  input:
    input_select_scene:
      name: Scene Selector
      description: The input_select entity used to choose the scenes.
      selector:
        entity:
          domain: input_select

  trigger: !input 'trigger'
  action:
    - service: input_select.select_next
      target:
        entity_id: !input 'input_select_scene'
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.' + input_select_scene) }}"
