blueprint:
  name: "Daan Dobber's Scene Cycle with input_select"
  description: Cycles through and activates scenes using a user-defined trigger. First make an input_select helper to define the scenes.
  domain: automation
  input:
    input_select_scene:
      name: Scene Selector
      description: The input_select entity used to choose the scenes.
      selector:
        entity:
          domain: input_select

automation:
  alias: "Daan Dobber's Scene Cycle with input_select"
  description: ""
  mode: restart
  # De trigger-sectie wordt hier zonder selector geplaatst, zodat de gebruiker de trigger kan kiezen bij het maken van de automatisering.
  trigger:
    - platform: state
      entity_id: !input 'input_select_scene'
  condition: []
  action:
    - service: input_select.select_next
      target:
        entity_id: !input 'input_select_scene'
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.' + input_select_scene) }}"
