blueprint:
  name: "Daan Dobber's Scene Cycle with input_select"
  description: Cycles through and activates scenes using a user-defined trigger. First make an input_select helper to define the scenes.
  domain: automation
  input:
    trigger:
      name: Trigger
      description: The trigger to cycle through the scenes.
      # De juiste syntaxis voor een gebruiker-gedefinieerde trigger is om gewoon "trigger" hier te laten, zonder de aanvullende "{}".
      selector:
        trigger: 

    input_select_scene:
      name: Scene Selector
      description: The input_select entity used to choose the scenes.
      selector:
        entity:
          domain: input_select

automation:
  alias: "Daan Dobber's Scene Cycle with input_select"
  description: ""
  mode: restart
  trigger: !input 'trigger'
  condition: []
  action:
    - service: input_select.select_next
      data:
        cycle: true
      target:
        entity_id: !input 'input_select_scene'
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states(input_select_scene.state) }}"
