blueprint:
  name: "Daan Dobber's Scene Cycle with input_select"
  description: Cycles through and activates scenes using a user-defined triggers. First make an input_select helper to define the scenes.
  domain: automation
  input:
    trigger_entities:
      name: Trigger Entities
      description: Choose the entities that will trigger the scene cycle.
      selector:
        entity:
          multiple: true

    input_select_scene:
      name: Scene Selector
      description: The input_select entity used to choose the scenes.
      selector:
        entity:
          domain: input_select

automation:
  alias: "Daan Dobber's Scene Cycle with input_select"
  description: "Cycles through and activates scenes using a user-defined triggers. First make an input_select helper to define the scenes."
  mode: restart
  trigger:
    - platform: state
      entity_id: !input 'trigger_entities'
  action:
    - service: input_select.select_next
      data:
        cycle: true
      target:
        entity_id: !input 'input_select_scene'
    - service: scene.turn_on
      data_template:
        entity_id: "{{ states('input_select.' ~ input_select_scene) }}"
